import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@6.5.1'
 *
 * Screen
 * Id: 8daf5516-ae90-402a-8fa5-bdf25f6c57e4
 * Codename: screen
 */
export type Screen = IContentItem<{
    /**
     * Content (text)
     * Required: false
     * Id: 49007286-ee94-44ca-bf64-f9a991dcc17f
     * Codename: content
     */
    content: Elements.TextElement;

    /**
     * Figma preview (custom)
     * Required: false
     * Id: 63c195e7-b7ef-49fd-8996-9c2f80a0c125
     * Codename: figma_preview
     */
    figmaPreview: Elements.CustomElement;

    /**
     * Figma URL (text)
     * Required: false
     * Id: 5d195cb4-0009-4c71-8fc6-5585d9a8243d
     * Codename: figma_url
     */
    figmaUrl: Elements.TextElement;

    /**
     * Image (asset)
     * Required: false
     * Id: 90bc248f-9e1a-44ca-86e2-a0b146e945e0
     * Codename: image
     */
    image: Elements.AssetsElement;

    /**
     * Title (text)
     * Required: false
     * Id: 060b7171-55b3-48ab-81d7-cbf587b474fc
     * Codename: title
     */
    title: Elements.TextElement;
}>;
