/**
 * Generated by '@kontent-ai/model-generator@6.5.1'
 */
export const contentTypes = {
    /**
     * Screen
     */
    screen: {
        codename: 'screen',
        id: '8daf5516-ae90-402a-8fa5-bdf25f6c57e4',
        externalId: undefined,
        name: 'Screen',
        elements: {
            /**
             * Content (text)
             */
            content: {
                codename: 'content',
                id: '49007286-ee94-44ca-bf64-f9a991dcc17f',
                externalId: undefined,
                name: 'Content',
                required: false,
                type: 'text'
            },

            /**
             * Figma preview (custom)
             */
            figma_preview: {
                codename: 'figma_preview',
                id: '63c195e7-b7ef-49fd-8996-9c2f80a0c125',
                externalId: undefined,
                name: 'Figma preview',
                required: false,
                type: 'custom'
            },

            /**
             * Figma URL (text)
             */
            figma_url: {
                codename: 'figma_url',
                id: '5d195cb4-0009-4c71-8fc6-5585d9a8243d',
                externalId: undefined,
                name: 'Figma URL',
                required: false,
                type: 'text'
            },

            /**
             * Image (asset)
             */
            image: {
                codename: 'image',
                id: '90bc248f-9e1a-44ca-86e2-a0b146e945e0',
                externalId: undefined,
                name: 'Image',
                required: false,
                type: 'asset'
            },

            /**
             * Title (text)
             */
            title: {
                codename: 'title',
                id: '060b7171-55b3-48ab-81d7-cbf587b474fc',
                externalId: undefined,
                name: 'Title',
                required: false,
                type: 'text'
            }
        }
    }
} as const;
